language: node_js
node_js:
  - 4
  - 6
  - 8

sudo: false
before_install:
  - cd .scripts/self-installer
  - npm i
  - npm run bundle
  - node install
script:
  - pnpm -v
  - pnpx -v
env:
  global:
    - CC=clang CXX=clang++ npm_config_clang=1
    - GIT_NAME: Travis CI
    - GIT_EMAIL: nobody@nobody.org
    - GITHUB_REPO: pnpm/pnpm
